
const P=[
['Servo Gate + 1 Ultrasonic','Gate','🚧','Automatic gate opens when an object comes near.',['Arduino Uno','Servo SG90','HC-SR04','Jumper wires'],['HC-SR04 VCC → 5V','HC-SR04 GND → GND','TRIG → D10','ECHO → D11','Servo signal → D9','Servo GND → GND'],`#include <Servo.h>\nServo gate;\nconst int trig=10,echo=11;\nvoid setup(){gate.attach(9);pinMode(trig,OUTPUT);pinMode(echo,INPUT);gate.write(0);}\nvoid loop(){\n digitalWrite(trig,LOW);delayMicroseconds(2);digitalWrite(trig,HIGH);delayMicroseconds(10);digitalWrite(trig,LOW);\n long us=pulseIn(echo,HIGH,30000); long cm=us*0.034/2;\n if(cm>0&&cm<30){gate.write(90);delay(1500);}else gate.write(0);\n}`],
['Servo Gate + 2 Ultrasonic','Gate','🚪','Two sensors detect vehicles from both sides.',['Arduino Uno','Servo','2 × HC-SR04','Jumper wires'],['Sensor 1 TRIG → D10','Sensor 1 ECHO → D11','Sensor 2 TRIG → D8','Sensor 2 ECHO → D12','Servo signal → D9','All GND → GND'],`#include <Servo.h>\nServo gate;\nlong cm(int t,int e){digitalWrite(t,LOW);delayMicroseconds(2);digitalWrite(t,HIGH);delayMicroseconds(10);digitalWrite(t,LOW);long u=pulseIn(e,HIGH,30000);return u?u*.034/2:999;}\nvoid setup(){gate.attach(9);pinMode(10,OUTPUT);pinMode(11,INPUT);pinMode(8,OUTPUT);pinMode(12,INPUT);gate.write(0);}\nvoid loop(){long a=cm(10,11),b=cm(8,12);if(a<30||b<30){gate.write(90);delay(1500);}else gate.write(0);}`],
['Automatic Street Light','LED','💡','LED turns on automatically when it gets dark.',['Arduino Uno','LDR','10k resistor','LED','220Ω resistor'],['LDR → 5V','LDR junction → A0','10k resistor A0 → GND','LED anode → D9 via 220Ω','LED cathode → GND'],`const int ldr=A0,led=9;\nvoid setup(){pinMode(led,OUTPUT);}\nvoid loop(){int light=analogRead(ldr);digitalWrite(led,light<500);delay(100);}`],
['Rain Detector + Buzzer','Sensor','🌧️','Detect rain and activate a buzzer.',['Arduino Uno','Rain sensor','Buzzer','LED'],['Rain VCC → 5V','Rain GND → GND','Rain AO → A0','Buzzer + → D8','Buzzer − → GND','LED anode → D9 via 220Ω'],`const int rain=A0,buzzer=8,led=9;\nvoid setup(){pinMode(buzzer,OUTPUT);pinMode(led,OUTPUT);}\nvoid loop(){bool wet=analogRead(rain)<600;digitalWrite(buzzer,wet);digitalWrite(led,wet);delay(200);}`],
['Ultrasonic Distance Meter','Sensor','📏','Measure distance using HC-SR04.',['Arduino Uno','HC-SR04','Serial Monitor'],['VCC → 5V','GND → GND','TRIG → D10','ECHO → D11'],`const int t=10,e=11;\nvoid setup(){pinMode(t,OUTPUT);pinMode(e,INPUT);Serial.begin(9600);}\nvoid loop(){digitalWrite(t,LOW);delayMicroseconds(2);digitalWrite(t,HIGH);delayMicroseconds(10);digitalWrite(t,LOW);long u=pulseIn(e,HIGH,30000);Serial.println(u*.034/2);delay(300);}`],
['Traffic Light','LED','🚦','Simple red, yellow and green traffic light.',['Arduino Uno','3 LEDs','3 × 220Ω resistors'],['Red → D8 via 220Ω','Yellow → D9 via 220Ω','Green → D10 via 220Ω','Cathodes → GND'],`int R=8,Y=9,G=10;\nvoid setup(){pinMode(R,OUTPUT);pinMode(Y,OUTPUT);pinMode(G,OUTPUT);}\nvoid loop(){digitalWrite(G,HIGH);delay(5000);digitalWrite(G,LOW);digitalWrite(Y,HIGH);delay(1500);digitalWrite(Y,LOW);digitalWrite(R,HIGH);delay(5000);digitalWrite(R,LOW);}`],
['Servo Motor Tester','Motor','⚙️','Control a servo with a potentiometer.',['Arduino Uno','Servo SG90','10k potentiometer'],['Pot middle → A0','Pot outer → 5V/GND','Servo signal → D9','Servo GND → GND'],`#include <Servo.h>\nServo s;\nvoid setup(){s.attach(9);}\nvoid loop(){s.write(map(analogRead(A0),0,1023,0,180));delay(15);}`],
['Button Controlled LED','LED','🔘','Press a button to turn an LED on.',['Arduino Uno','Push button','LED','220Ω resistor'],['Button → D2 and GND','LED anode → D9 via 220Ω','LED cathode → GND'],`const int b=2,led=9;\nvoid setup(){pinMode(b,INPUT_PULLUP);pinMode(led,OUTPUT);}\nvoid loop(){digitalWrite(led,digitalRead(b)==LOW);}`],
['PIR Motion Alarm','Security','🚨','Detect motion and sound a buzzer.',['Arduino Uno','PIR HC-SR501','Buzzer','LED'],['PIR VCC → 5V','PIR GND → GND','PIR OUT → D2','Buzzer + → D8','LED → D9 via 220Ω'],`const int pir=2,bz=8,led=9;\nvoid setup(){pinMode(pir,INPUT);pinMode(bz,OUTPUT);pinMode(led,OUTPUT);}\nvoid loop(){bool m=digitalRead(pir);digitalWrite(bz,m);digitalWrite(led,m);}`],
['Soil Moisture Detector','Home','🌱','Warn when a plant needs water.',['Arduino Uno','Soil sensor','LED','Buzzer'],['Sensor VCC → 5V','GND → GND','AO → A0','LED → D9 via 220Ω','Buzzer → D8'],`int soil=A0;\nvoid setup(){pinMode(8,OUTPUT);pinMode(9,OUTPUT);}\nvoid loop(){bool dry=analogRead(soil)>650;digitalWrite(8,dry);digitalWrite(9,dry);}`],
['Potentiometer LED Dimmer','LED','🎚️','Use a knob to control LED brightness.',['Arduino Uno','10k potentiometer','LED','220Ω resistor'],['Pot middle → A0','Pot outer → 5V/GND','LED anode → D9 via 220Ω','LED cathode → GND'],`void setup(){pinMode(9,OUTPUT);}\nvoid loop(){analogWrite(9,map(analogRead(A0),0,1023,0,255));}`],
['Automatic Door PIR + Servo','Security','🚪','Motion opens a small servo door.',['Arduino Uno','PIR sensor','Servo'],['PIR VCC → 5V','PIR GND → GND','PIR OUT → D2','Servo signal → D9','Servo GND → GND'],`#include <Servo.h>\nServo door;\nvoid setup(){door.attach(9);pinMode(2,INPUT);door.write(0);}\nvoid loop(){if(digitalRead(2)){door.write(90);delay(2500);door.write(0);}}`],
['RGB LED Color Mixer','LED','🌈','Mix RGB channels using potentiometers.',['Arduino Uno','RGB LED','3 × 220Ω','3 potentiometers'],['R → D9 via 220Ω','G → D10 via 220Ω','B → D11 via 220Ω','Pot wipers → A0,A1,A2','Common cathode → GND'],`void setup(){pinMode(9,OUTPUT);pinMode(10,OUTPUT);pinMode(11,OUTPUT);}\nvoid loop(){analogWrite(9,map(analogRead(A0),0,1023,0,255));analogWrite(10,map(analogRead(A1),0,1023,0,255));analogWrite(11,map(analogRead(A2),0,1023,0,255));}`],
['Buzzer Doorbell','Home','🔔','Press a button to play a doorbell tone.',['Arduino Uno','Push button','Buzzer'],['Button → D2 and GND','Buzzer + → D8','Buzzer − → GND'],`void setup(){pinMode(2,INPUT_PULLUP);}\nvoid loop(){if(!digitalRead(2)){tone(8,1000,200);delay(220);tone(8,1400,250);delay(300);}}`],
['Parking Sensor','Sensor','🅿️','Distance warning using LEDs and buzzer.',['Arduino Uno','HC-SR04','3 LEDs','Buzzer'],['TRIG → D10','ECHO → D11','Green → D5','Yellow → D6','Red → D7','Buzzer → D8'],`long cm(){digitalWrite(10,LOW);delayMicroseconds(2);digitalWrite(10,HIGH);delayMicroseconds(10);digitalWrite(10,LOW);return pulseIn(11,HIGH)*.034/2;}\nvoid setup(){pinMode(10,OUTPUT);pinMode(11,INPUT);for(int p=5;p<=8;p++)pinMode(p,OUTPUT);}\nvoid loop(){long d=cm();for(int p=5;p<=7;p++)digitalWrite(p,LOW);noTone(8);if(d<10){digitalWrite(7,HIGH);tone(8,1500);}else if(d<25)digitalWrite(6,HIGH);else digitalWrite(5,HIGH);}`],
['LED Chase Effect','Game','✨','Eight LEDs create a running light.',['Arduino Uno','8 LEDs','8 × 220Ω resistors'],['LEDs anodes → D2-D9 via 220Ω','Cathodes → GND'],`int p[]={2,3,4,5,6,7,8,9};\nvoid setup(){for(int i=0;i<8;i++)pinMode(p[i],OUTPUT);}\nvoid loop(){for(int i=0;i<8;i++){digitalWrite(p[i],1);delay(80);digitalWrite(p[i],0);}for(int i=6;i>0;i--){digitalWrite(p[i],1);delay(80);digitalWrite(p[i],0);}}`],
['Touch Sensor LED','Home','👆','Touch TTP223 to switch an LED.',['Arduino Uno','TTP223','LED','220Ω resistor'],['TTP223 VCC → 5V','GND → GND','OUT → D2','LED → D9 via 220Ω'],`void setup(){pinMode(2,INPUT);pinMode(9,OUTPUT);}\nvoid loop(){digitalWrite(9,digitalRead(2));}`],
['Servo Sweep','Motor','🔄','Smoothly move a servo from 0 to 180 degrees.',['Arduino Uno','Servo SG90'],['Signal → D9','VCC → 5V/external supply','GND → GND'],`#include <Servo.h>\nServo s;\nvoid setup(){s.attach(9);}\nvoid loop(){for(int a=0;a<=180;a++){s.write(a);delay(10);}for(int a=180;a>=0;a--){s.write(a);delay(10);}}`],
['Serial LED Control','Game','⌨️','Type ON or OFF in Serial Monitor.',['Arduino Uno','LED','220Ω resistor'],['LED anode → D13','LED cathode → GND'],`void setup(){pinMode(13,OUTPUT);Serial.begin(9600);}\nvoid loop(){if(Serial.available()){String s=Serial.readStringUntil('\\n');s.trim();s.toUpperCase();if(s=="ON")digitalWrite(13,HIGH);if(s=="OFF")digitalWrite(13,LOW);}}`],
['DHT11 Temperature Monitor','Display','🌡️','Read temperature and humidity from DHT11.',['Arduino Uno','DHT11','16x2 LCD optional'],['DHT VCC → 5V','DHT GND → GND','DHT DATA → D2'],`// Install the DHT sensor library first.\n#include <DHT.h>\nDHT dht(2,DHT11);\nvoid setup(){Serial.begin(9600);dht.begin();}\nvoid loop(){Serial.print("Temp: ");Serial.println(dht.readTemperature());delay(2000);}`],
['Bluetooth LED Control','Home','📱','Control an LED from a Bluetooth serial module.',['Arduino Uno','HC-05/HC-06','LED','220Ω resistor'],['HC-05 VCC → 5V','GND → GND','TX → Arduino RX (use proper level shifting as needed)','LED → D13'],`void setup(){pinMode(13,OUTPUT);Serial.begin(9600);}\nvoid loop(){if(Serial.available()){char c=Serial.read();if(c=='1')digitalWrite(13,HIGH);if(c=='0')digitalWrite(13,LOW);}}`],
['Line Following Robot','Robot','🤖','Basic two-sensor line follower using an L298N.',['Arduino Uno','L298N','2 IR sensors','2 DC motors','Battery'],['IR left OUT → D2','IR right OUT → D3','L298N IN1/IN2 → D8/D9','L298N IN3/IN4 → D10/D11','Motor outputs → motors','Common GND → GND'],`const int L=2,R=3;\nvoid setup(){pinMode(L,INPUT);pinMode(R,INPUT);for(int p=8;p<=11;p++)pinMode(p,OUTPUT);}\nvoid loop(){int l=digitalRead(L),r=digitalRead(R);if(l==0&&r==0)forward();else if(l==0)left();else if(r==0)right();else stopMotors();}\nvoid forward(){digitalWrite(8,1);digitalWrite(9,0);digitalWrite(10,1);digitalWrite(11,0);}\nvoid left(){digitalWrite(8,0);digitalWrite(9,0);digitalWrite(10,1);digitalWrite(11,0);}\nvoid right(){digitalWrite(8,1);digitalWrite(9,0);digitalWrite(10,0);digitalWrite(11,0);}\nvoid stopMotors(){for(int p=8;p<=11;p++)digitalWrite(p,0);}`],
['Mini Weather Station','Display','🌤️','Read temperature and humidity and show the values in Serial Monitor.',['Arduino Uno','DHT11','Jumper wires'],['DHT VCC → 5V','DHT GND → GND','DHT DATA → D2'],`#include <DHT.h>
DHT dht(2,DHT11);
void setup(){Serial.begin(9600);dht.begin();}
void loop(){Serial.print("Temperature: ");Serial.print(dht.readTemperature());Serial.print(" C  Humidity: ");Serial.println(dht.readHumidity());delay(2000);}`],
['RFID Door Lock','Security','🔐','Use an RFID card to unlock a servo-controlled door.',['Arduino Uno','RC522 RFID','Servo SG90','Buzzer'],['RC522 SDA → D10','SCK → D13','MOSI → D11','MISO → D12','RST → D9','Servo signal → D6','All GND → GND'],`// Install MFRC522 library.
#include <SPI.h>
#include <MFRC522.h>
#include <Servo.h>
MFRC522 r(10,9); Servo lockServo;
void setup(){SPI.begin();r.PCD_Init();lockServo.attach(6);lockServo.write(0);}
void loop(){if(!r.PICC_IsNewCardPresent()||!r.PICC_ReadCardSerial())return;lockServo.write(90);delay(2500);lockServo.write(0);r.PICC_HaltA();}`],
['Smart Home Light','Home','🏠','Turn a light on automatically when motion is detected.',['Arduino Uno','PIR sensor','Relay module','LED/load'],['PIR VCC → 5V','PIR GND → GND','PIR OUT → D2','Relay IN → D8','Relay VCC → 5V','Relay GND → GND'],`const int pir=2,relay=8;
void setup(){pinMode(pir,INPUT);pinMode(relay,OUTPUT);}
void loop(){digitalWrite(relay,digitalRead(pir));}`],
['Clap Switch','Game','👏','Turn an LED on when a sound sensor detects a clap.',['Arduino Uno','Sound sensor','LED','220Ω resistor'],['Sound OUT → D2','VCC → 5V','GND → GND','LED → D9 via 220Ω'],`const int sound=2,led=9;
void setup(){pinMode(sound,INPUT);pinMode(led,OUTPUT);}
void loop(){if(digitalRead(sound)){digitalWrite(led,!digitalRead(led));delay(300);}}`],
['LCD Distance Display','Display','📺','Show HC-SR04 distance on a 16x2 I2C LCD.',['Arduino Uno','HC-SR04','16x2 I2C LCD'],['TRIG → D10','ECHO → D11','LCD SDA → A4','LCD SCL → A5','VCC → 5V','GND → GND'],`// Install LiquidCrystal_I2C library.
#include <Wire.h>
#include <LiquidCrystal_I2C.h>
LiquidCrystal_I2C lcd(0x27,16,2);
void setup(){pinMode(10,OUTPUT);pinMode(11,INPUT);lcd.init();lcd.backlight();}
void loop(){digitalWrite(10,LOW);delayMicroseconds(2);digitalWrite(10,HIGH);delayMicroseconds(10);digitalWrite(10,LOW);long u=pulseIn(11,HIGH,30000);float d=u*.034/2;lcd.clear();lcd.print("Distance: ");lcd.print(d);lcd.print(" cm");delay(300);}`],
['Mini Piano','Game','🎹','Play different tones with four push buttons.',['Arduino Uno','4 push buttons','Buzzer'],['Buttons → D2,D3,D4,D5 and GND','Buzzer + → D8','Buzzer − → GND'],`int keys[]={2,3,4,5};int notes[]={262,330,392,523};
void setup(){for(int i=0;i<4;i++)pinMode(keys[i],INPUT_PULLUP);}
void loop(){for(int i=0;i<4;i++)if(!digitalRead(keys[i]))tone(8,notes[i]);else noTone(8);}`],
['Obstacle Avoiding Robot','Robot','🚗','Drive forward and turn when an obstacle is detected.',['Arduino Uno','HC-SR04','L298N','2 DC motors'],['TRIG → D10','ECHO → D11','L298N IN1/IN2 → D8/D9','L298N IN3/IN4 → D12/D13','Motors → outputs','Common GND → GND'],`const int t=10,e=11;
void setup(){pinMode(t,OUTPUT);pinMode(e,INPUT);for(int p: {8,9,12,13})pinMode(p,OUTPUT);}
long distanceCM(){digitalWrite(t,LOW);delayMicroseconds(2);digitalWrite(t,HIGH);delayMicroseconds(10);digitalWrite(t,LOW);long u=pulseIn(e,HIGH,30000);return u?u*.034/2:999;}
void loop(){long d=distanceCM();if(d<20){digitalWrite(8,0);digitalWrite(9,1);digitalWrite(12,1);digitalWrite(13,0);delay(450);}else{digitalWrite(8,1);digitalWrite(9,0);digitalWrite(12,1);digitalWrite(13,0);}}`],
['Water Level Alarm','Sensor','💧','Warn when a water level sensor detects water.',['Arduino Uno','Water level sensor','Buzzer','LED'],['Sensor VCC → 5V','GND → GND','AO → A0','Buzzer + → D8','LED → D9 via 220Ω'],`const int sensor=A0,bz=8,led=9;
void setup(){pinMode(bz,OUTPUT);pinMode(led,OUTPUT);}
void loop(){bool high=analogRead(sensor)>500;digitalWrite(bz,high);digitalWrite(led,high);delay(100);}`]
];
let codeNow='';const intro=document.getElementById('intro'),app=document.getElementById('app');function enter(n){saveVisitor(n);localStorage.setItem('anmolName',n);document.getElementById('welcome').textContent=n;document.getElementById('sideName').textContent=n.toUpperCase();intro.classList.add('hidden');app.classList.remove('hidden')};const old=localStorage.getItem('anmolName');if(old)enter(old);document.getElementById('nameInput').oninput=e=>{document.getElementById('continue').disabled=!e.target.value.trim();document.getElementById('continue').classList.toggle('active',!!e.target.value.trim())};document.getElementById('continue').onclick=()=>enter(document.getElementById('nameInput').value.trim());
const grid=document.getElementById('grid'),search=document.getElementById('search'),cat=document.getElementById('cat');function render(){let q=search.value.toLowerCase(),c=cat.value;let list=P.filter(x=>(c==='All'||x[1]===c)&&(x[0].toLowerCase().includes(q)||x[3].toLowerCase().includes(q)||x[4].join(' ').toLowerCase().includes(q)));document.getElementById('count').textContent=list.length+' projects';grid.innerHTML=list.map((p,i)=>`<article class="card"><div class="pic">${p[2]}</div><div class="body">${i<4?'<span class="badge">FEATURED</span>':''}<h4>${p[0]}</h4><p>${p[3]}</p><b style="font-size:11px">🧰 Components</b><div class="chips">${p[4].map(x=>`<span class="chip">${x}</span>`).join('')}</div><div class="actions"><button class="small" onclick="openProject(${P.indexOf(p)})">📄 Code</button><button class="small" onclick="openProject(${P.indexOf(p)})">🔌 Wiring</button><button class="small primary" onclick="openProject(${P.indexOf(p)})">View →</button></div></div></article>`).join('')||'<div style="grid-column:1/-1" class="detail">No project found.</div>'}search.oninput=render;cat.onchange=render;document.querySelectorAll('.nav button').forEach(b=>b.onclick=()=>{document.querySelectorAll('.nav button').forEach(x=>x.classList.remove('active'));b.classList.add('active');cat.value=b.dataset.cat;render()});
function openProject(i){let p=P[i];document.getElementById('mbadge').textContent=p[1];document.getElementById('mtitle').textContent=p[0];document.getElementById('mdesc').textContent=p[3];document.getElementById('mcomp').innerHTML=p[4].map(x=>`<span class="chip" style="display:inline-block;margin:3px">${x}</span>`).join('');document.getElementById('mhow').textContent='Connect the components exactly as shown, select your board, upload the code, then test the project step by step.';document.getElementById('mwire').innerHTML=p[5].map(x=>`<div class="wire">🔗 ${x}</div>`).join('');document.getElementById('mcode').textContent=p[6];codeNow=p[6];document.getElementById('modal').classList.remove('hidden')}function closeModal(){document.getElementById('modal').classList.add('hidden')}function copyCode(){navigator.clipboard?.writeText(codeNow);toast('Code copied!')}function toast(s){let t=document.getElementById('toast');t.textContent=s;t.classList.remove('hidden');setTimeout(()=>t.classList.add('hidden'),2000)}document.getElementById('popular').innerHTML=P.slice(0,5).map((p,i)=>`<button onclick="openProject(${i})">${p[2]} ${p[0]} ›</button>`).join('');
let port=null;document.getElementById('connect').onclick=async()=>{if(!('serial' in navigator)){toast('Web Serial is not supported here. Use Chrome/Edge on desktop.');return}try{if(port){await port.close();port=null;document.getElementById('status').textContent='● Not Connected';document.getElementById('status').classList.remove('ok');document.getElementById('connect').textContent='Connect';return}port=await navigator.serial.requestPort();await port.open({baudRate:9600});document.getElementById('status').textContent='● Arduino Connected';document.getElementById('status').classList.add('ok');document.getElementById('connect').textContent='Disconnect';toast('Your Arduino is connected!')}catch(e){toast('Connection cancelled or failed.')}};

const VISITOR_PASSWORD='1234'; // Change this password in the code if you want.
function saveVisitor(name){
  const key='anmolVisitors';
  const list=JSON.parse(localStorage.getItem(key)||'[]');
  list.push({name:name, time:new Date().toLocaleString()});
  localStorage.setItem(key,JSON.stringify(list));
}
function openVisitorAuth(){document.getElementById('visitorPassword').value='';document.getElementById('passwordError').style.display='none';document.getElementById('visitorAuth').classList.remove('hidden');setTimeout(()=>document.getElementById('visitorPassword').focus(),50)}
function closeVisitorAuth(){document.getElementById('visitorAuth').classList.add('hidden')}
function unlockVisitors(){if(document.getElementById('visitorPassword').value===VISITOR_PASSWORD){closeVisitorAuth();refreshVisitors();document.getElementById('visitorPanel').classList.remove('hidden')}else document.getElementById('passwordError').style.display='block'}
function closeVisitors(){document.getElementById('visitorPanel').classList.add('hidden')}
function refreshVisitors(){
 const list=JSON.parse(localStorage.getItem('anmolVisitors')||'[]');
 const el=document.getElementById('visitorList');
 if(!list.length){el.innerHTML='<div class="visitor-empty">No visitors saved yet.</div>';return}
 el.innerHTML=list.slice().reverse().map((v,i)=>`<div class="visitor-row"><div>👤 <b>${escapeHtml(v.name)}</b></div><small>${escapeHtml(v.time)}</small></div>`).join('');
}
function clearVisitors(){if(confirm('Clear all saved visitor names from this browser?')){localStorage.removeItem('anmolVisitors');refreshVisitors();toast('Visitor history cleared.')}}
function escapeHtml(x){return String(x).replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#039;'}[m]))}
document.getElementById('visitorsBtn').onclick=openVisitorAuth;
document.getElementById('visitorPassword').addEventListener('keydown',e=>{if(e.key==='Enter')unlockVisitors()});

render();
